   name: Build Project
   on:
     push:
       branches:
         - trunk
   jobs:
     build:
       runs - on: ubuntu - latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: Setup CMake
           uses: jwlawson/actions - cmake@v1.5
           with:
             cmake - version: '3.20'
         - name: Setup Clang
           run: |
             sudo apt - get update
             sudo apt - get install - y clang
         - name: Build
           run: |
             mkdir build
             cd build
             cmake.. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
             make
